using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace localink_be.Models.Entities
{
    public class User 
    {
        [Key]
        public long UserId { get; set; }
        public string AccountType { get; set; } = null!;
        public string FullName { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string? PhoneNumber { get; set; }
        public string CountryCode { get; set; } = string.Empty;
        public string? PasswordHash { get; set; }

        public int? OtpAttempts { get; set; }
        public string? PasswordResetOtp { get; set; }
        public DateTime? OtpExpiry { get; set; }
        public string? ProfilePicture { get; set; }
        
        // Track authentication provider (email, google, etc.)
        public string? AuthProvider { get; set; }
        public string? ProviderId { get; set; }
        
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// True after the user explicitly accepts the User Agreement on the consent screen.
        /// New accounts default to false until accepted.
        /// </summary>
        public bool ConsentAccepted { get; set; }

        /// <summary>
        /// Permanent unique share code (e.g. VFS-AB12CD). Generated by backend; not client-editable.
        /// Nullable until backfill for legacy users.
        /// </summary>
        [MaxLength(16)]
        public string? ReferralCode { get; set; }

        /// <summary>
        /// User who successfully referred this account. Immutable once set.
        /// </summary>
        public long? ReferredByUserId { get; set; }

        /// <summary>
        /// Denormalized count of verified successful referrals (registration attributions).
        /// Updated only by backend when a referral_history row is created.
        /// </summary>
        public int SuccessfulReferralCount { get; set; }

        [ForeignKey(nameof(ReferredByUserId))]
        public User? ReferredByUser { get; set; }

        public ICollection<Business> Businesses { get; set; } = new List<Business>();
    }
}